name: Prek checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run prek
        uses: j178/prek-action@v3.0.0
